name: Deploy MkDocs Site

on:
  push:
    branches: [ main ] # 当推送到 main 分支时触发

permissions:
  contents: write # 允许部署到 gh-pages 分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # 安装 mkdocs 和相关主题

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
